server:
  port: 8081
#  servlet:
#    context-path: /deviceAlarm
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mvc:
    view:
      prefix: /
      suffix: .html
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ananops_alarm?serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

